spring:
  application:
    name: player-service
  datasource:
    url: jdbc:mysql://web-videogame-db.mysql.database.azure.com:3306/videojuegop6
    username: mike
    password: d3PYvKAZ8yjNxj8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT:8081}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-hcf9b7ajdva0h9bs.mexicocentral-01.azurewebsites.net/eureka/
  instance:
    prefer-ip-address: true
    #ip-address: 127.0.0.1  # O la IP local de la máquina
